name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            sparse-checkout: .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'

      - name: server
        run:  cd server


      - name: Install production dependencies
        run: npm install --production

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./

      - name: Run tests
        run: npm test

